In [226]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

true_w=torch.tensor([2,-3.4,10])
true_b=4.2
features,labels=d2l.synthetic_data(true_w,true_b,1000)

In [227]:
def load_array(data_arrays,batch_size,is_train=True):
    dataset=data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset,batch_size,shuffle=is_train)

batch_size=10
data_iter=load_array((features,labels),batch_size)

In [228]:
next(iter(data_iter))

[tensor([[-1.2215,  0.1432, -1.6500],
         [ 0.3763,  0.2664,  0.4970],
         [ 0.4764,  0.1718,  0.2901],
         [ 0.1090,  0.3923, -0.2394],
         [ 0.3877,  1.4412, -1.4538],
         [ 0.1285,  0.0552, -1.4677],
         [ 1.3549, -0.0565,  1.2055],
         [-0.7720, -0.5344, -1.4155],
         [-1.8949, -0.0739,  0.8071],
         [ 1.4423,  1.7267, -0.4387]]),
 tensor([[-15.2286],
         [  9.0064],
         [  7.4747],
         [  0.6949],
         [-14.4694],
         [-10.4259],
         [ 19.1565],
         [ -9.6729],
         [  8.7331],
         [ -3.1718]])]

In [229]:
from torch import nn
net=nn.Sequential(nn.Linear(3,1))#决定输入特征和输出特征的形状,都是n*1

In [230]:
net[0].weight.data.normal_(0,0.01)#因为均值为0,方差为0.01,说明生成的权重几乎全为0
print(net[0].weight.data)
net[0].bias.data.fill_(0)

tensor([[ 0.0012, -0.0005,  0.0024]])


tensor([0.])

In [231]:
#定义损失函数
loss=nn.MSELoss(reduction='mean')
trainer=torch.optim.SGD(net.parameters(),lr=0.03)#管理了net的所有参数和梯度

In [232]:
num_epoch=5

for i in range(num_epoch):
    for x,y in data_iter:
        # print("1  ",net[0].weight.grad)
        trainer.zero_grad()#因为要在backward之前把上一轮的梯度给去掉
        # print("2  ",net[0].weight.grad)
        l=loss(net(x),y)#l是矩阵,如果loss改为nn.MSELoss(reduction="sum"),那么返回的是一个标量
        print(l)
        # print("3  ",net[0].weight.grad)        
        l.backward()#只有调用了backward(),优化器所管理的参数的梯度才会改变
        # print("4  ",net[0].weight.grad)
        trainer.step()#都是小批量随机梯度下降
        # print("5  ",net[0].weight.grad)
    l=loss(net(features),labels)
    print(f"epoch{i+1},loss{l:.5f}")


1   None
2   None
tensor(105.6785, grad_fn=<MseLossBackward>)
3   None
4   tensor([[ -6.0577,   5.9792, -17.3612]])
5   tensor([[ -6.0577,   5.9792, -17.3612]])
1   tensor([[ -6.0577,   5.9792, -17.3612]])
2   tensor([[0., 0., 0.]])
tensor(209.4845, grad_fn=<MseLossBackward>)
3   tensor([[0., 0., 0.]])
4   tensor([[ -7.8153,   8.6087, -32.4280]])
5   tensor([[ -7.8153,   8.6087, -32.4280]])
1   tensor([[ -7.8153,   8.6087, -32.4280]])
2   tensor([[0., 0., 0.]])
tensor(55.9447, grad_fn=<MseLossBackward>)
3   tensor([[0., 0., 0.]])
4   tensor([[-6.2648,  3.3210, -7.1024]])
5   tensor([[-6.2648,  3.3210, -7.1024]])
1   tensor([[-6.2648,  3.3210, -7.1024]])
2   tensor([[0., 0., 0.]])
tensor(141.8987, grad_fn=<MseLossBackward>)
3   tensor([[0., 0., 0.]])
4   tensor([[ -2.3558,   2.0583, -28.9497]])
5   tensor([[ -2.3558,   2.0583, -28.9497]])
1   tensor([[ -2.3558,   2.0583, -28.9497]])
2   tensor([[0., 0., 0.]])
tensor(37.8741, grad_fn=<MseLossBackward>)
3   tensor([[0., 0., 0.]])
4   tens